# Generated by Django 2.2.6 on 2019-10-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cnname', models.CharField(max_length=100)),
                ('enname', models.CharField(max_length=100)),
                ('population', models.CharField(max_length=50)),
                ('area', models.CharField(max_length=50)),
                ('locationarea', models.CharField(choices=[('1', 'Asia'), ('2', 'Europe'), ('3', 'South America'), ('4', 'North America'), ('5', 'Africa'), ('6', 'Oceania'), ('7', 'Antarctica')], max_length=1)),
                ('desc_basic', models.TextField()),
                ('desc_weather', models.TextField()),
                ('desc_economy', models.TextField()),
                ('desc_onlinebusiness', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CountryFestivals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cn_name', models.CharField(max_length=100)),
                ('en_name', models.CharField(max_length=100)),
                ('startdate', models.DateField()),
                ('enddate', models.DateField()),
                ('desc', models.TextField()),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessCountry.CountryList')),
            ],
        ),
        migrations.CreateModel(
            name='Countryfavor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialCategory', models.IntegerField()),
                ('favorProd', models.TextField()),
                ('category1', models.ManyToManyField(to='Products.CategoryLevel1')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BusinessCountry.CountryList')),
            ],
        ),
    ]
