# Generated by Django 2.2.6 on 2019-10-16 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ECommercePlatforms',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('found_company', models.CharField(max_length=255)),
                ('found_time', models.DateField()),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Weblinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linkname', models.CharField(max_length=255)),
                ('countryID', models.IntegerField()),
                ('eCommercePlatforms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ECommercePlatforms.ECommercePlatforms')),
            ],
        ),
    ]
