# Generated by Django 2.2.6 on 2019-10-16 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryLevel1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category1', models.CharField(max_length=100)),
                ('category1desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel2',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category2', models.CharField(max_length=100)),
                ('category2desc', models.TextField()),
                ('category1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.CategoryLevel1')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryLevel3',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category3', models.CharField(max_length=100)),
                ('category3desc', models.TextField()),
                ('category2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Products.CategoryLevel2')),
            ],
        ),
    ]
